version: '3.8'
services:
  capstone:
    build:
      context: .
      args:
        NB_USER: $NB_USER
        NB_UID: $NB_UID
      dockerfile: DockerFile
    environment:
      - JUPYTER_TOKEN=hi
    ports:
      - 8888:8888
    container_name: capstone
